Description: Configuration for Adapter participant for SIL Kit Adapter GPIO demo
ParticipantName: CANoe_device
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
