version: 2.2.0

global-settings:
 time-source: internal-realtime
 default-network-mapping: external-sil-kit

datasources:
  input-files:
  - file-path: ../CANoe/Datasource_device.vcdl

sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../SilKitConfig_CANoe.silkit.yaml