Description: Configuration for Adapter participant for SIL Kit Adapter GLIO chardev demo
ParticipantName: GLIO_chardev_device
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
