# Configuration for the following chips :
#
# /path/to/adchips/adchip0/
# |-- in_voltage103
# |-- in_voltage15
# |-- out_voltage32
#
# /path/to/adchips/adchip1/
# |-- out_voltage5
# |-- PIN12
# |   |-- value
# |   `-- direction
# 
advalues:
- path: "./advalues/demos/adchips/adchip0/"
  int16_t:
  - files:
    - name: in_voltage103
      topic_subscribe: toVoltage103
    - name: in_voltage15
      topic_subscribe: toVoltage15
      topic_publish: fromVoltage15
    - name: out_voltage32
      topic_publish: fromVoltage32
- path: "./advalues/demos/adchips/adchip1/"
  uint8_t:
  - files:
    - name: PIN12/value
      topic_subscribe: toPIN12Value
      topic_publish: fromPIN12Value
    - name: PIN12/direction
      topic_subscribe: toPIN12Dir
      topic_publish: fromPIN12Dir
  double:
  - files:
    - name: out_voltage5
      topic_subscribe: toVoltage5