Description: Configuration for Adapter participant for SIL Kit Adapter GLIO advalues demo
ParticipantName: GLIO_advalues_device
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
