name: 'Linux Release Build'

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux-release:
    name: Build SIL Kit GLIO for Release configuration
    environment: public-github-runners
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        uses: ./.github/actions/build-cmake-preset
        with:
          preset-name: linux-release
          cmake-args:  "-D PACKAGE_FILENAME_SUFFIX=-${{ github.ref_name }}-ubuntu-20.04-x86_64-gcc"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: true
          files: |
            _build/linux-release/SilKit-Adapters*.zip
