name: trigger SIL Kit Adapters pipeline tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  
jobs:
  call-testing-workflow:
    uses: pnd/sil-kit-adapters-ci-testing/.github/workflows/container-reusable.yml@main
    with:
      repository_under_test : ${{ github.repository }}
      branch_under_test: ${{ github.event.pull_request.head.ref }}
      ci_testing_branch: main
      adapter_name: |
        advalues
        chardev
        gpio
        adapter
      canoe4sw_se_scripts_dir: demos/CANoe4SW_SE
    secrets: inherit
